### ISSUE TITLE
Problem with the sprite atlas creation in the sprite doc examples

### ISSUE THREAD

**Issue by RychuP** [craftworkgames/website#77]
The examples in the Sprite doc do not compile. The issue is the change from:

`_atlas = Texture2DAtlas.Create("Atlas/Cards", cardsTexture, 32, 32);`

to:

`_atlas = new Texture2DAtlas(cardsTexture);`
`_atlas.CreateRegion(11, 68, 42, 60);`

which causes `.CreateSprite` methods to throw exceptions.

**Comment by AristurtleDev** [comment]
Resolved in #78
